server:
  listen: 8080
  workers: 4

  upstream:
    - id: node1
      server: localhost:8001

    - id: node2
      server: localhost:8002

    - id: node3
      server: localhost:8003

  rules:
    - path: /
      upstream: 
        - node1
        - node3

    - path: /get
      upstream: 
        - node2
