server:
  listen: 8080
  workers: 4

  upstream:
    - id: node1
      server: localhost:8001

    - id: node2
      server: localhost:8002

  rules:
    - path: /
      upstream: 
        - node1

    - path: /get
      upstream: 
        - node2
