server:
  listen: 8080
  workers: 4

  upstream:
    - id: node1
      server: https://jsonplaceholder.typicode.com/todos/1

    - id: node2
      server: https://jsonplaceholder.typicode.com/todos/2

    - id: node3
      server: https://jsonplaceholder.typicode.com/todos/1

    - id: node4
      server: https://jsonplaceholder.typicode.com/todos/5

  rules:
    - path: /
      upstream: 
        - node1
        - node3

    - path: /todo
      upstream: 
        - node2

    - path: /auth
      upstream:
        - node4
